# Generated by Django 5.0.1 on 2024-05-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_product_cover_image_product_quantity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variant',
            unique_together={('product', 'name')},
        ),
    ]
